package page

const ID_SELECT = "[name*='IdPiso']"
const THUMB_SELECT = ".frame.slideShow img"
const PHOTO_URL_PRE = "http://fotos.imghs.net/"
const PHOTO_REGEXP = "(s|m|l|xl)"
const TELF_ENC_SELECT = "[id='tlfEnc']"
const TELF_TXT_SELECT = ".number.one"
const INMO_SELECT = ".line.noMargin a[href^='/inmobiliaria']"
const DESC_BOD_SELECT = ".descriptionBlock .description"
const DATA_SELECT = "div.block"
const DATA_TITL_BASIC = "Datos básicos"
const DATA_TITL_EQUIP = "Equipamiento e instalaciones"
const DATA_TITL_CERTIFY = "Certificado energético"
const DATA_TITL_EXT = "Exteriores"
const DATA_TITL_FURN = "Muebles y acabados"
const DATA_TITL_SELECT = "h5"
const DATA_LINE_SELECT = "div.line"
const DATA_LINE_REGEXP = "^(.*):(.*)"
const DATA_AREA_KEY = "Superficie"
const DATA_ROOMS_KEY = "Habitaciones"
const DATA_BATHS_KEY = "Baños"
const DATA_FLOOR_KEY = "Planta"
const DATA_AGE_KEY = "Antigüedad"
const DATA_MAINT_KEY = "Conservación"
const DATA_COM_FEES_KEY = "Gastos de comunidad"
const DATA_N_REGEXP = "\\d+"
const DATA_AREA_REGEXP = "(\\d+)( m² construidos)?( / )?(\\d+)?( m² útiles)?"
const DATA_LESS_5_Y_REGEXP = "Menos de 5 años"
const DATA_B_5_10_Y_REGEXP = "Entre 5 y 10 años"
const DATA_B_10_20_Y_REGEXP = "Entre 10 y 20 años"
const DATA_B_20_30_Y_REGEXP = "Entre 20 y 30 años"
const DATA_B_30_50_Y_REGEXP = "Entre 30 y 50 años"
const DATA_MORE_50_Y_REGEXP = "Más de 50 años"
const DATA_B_10_20_E_REGEXP = "entre 10 y 20 €"
const DATA_B_20_40_E_REGEXP = "entre 20 y 40 €"
const DATA_B_40_60_E_REGEXP = "entre 40 y 60 €"
const DATA_B_60_80_E_REGEXP = "entre 60 y 80 €"
const DATA_B_80_100_E_REGEXP = "entre 80 y 100 €"
const DATA_MORE_100_E_REGEXP = "más de 100 €"

